Upgrade to Elm 0.19
dividat/elm-identicon pull request #1
Opened 2019-10-08 15:36 UTC by krksgbr

### [Trello card](https://trello.com/c/EBoBkZbH/485-elm-019-migrate-pukkamustard-elm-identicon)

I tested the example with `elm reactor` and it produces the same images as previously.

2019-10-14 11:03 UTC, knuton requested changes
Code looks good!

Version number needs to be left unchanged. Might avoid future nuisance not to pin the Elm version down so precisely in the example `elm.json`.

2019-10-14 11:03 UTC, knuton commented on elm.json
> +    "version": "4.0.0",
This should be left at `3.0.0`. `elm bump` will want to make this into `3.0.1`, as the API is unchanged.

2019-10-14 11:03 UTC, knuton commented on example/elm.json
> +    "elm-version": "0.19.0",
Why so precise?

2019-10-14 13:29 UTC, krksgbr commented on elm.json
> +    "version": "4.0.0",
Since the package has been renamed from `pukkamustard/elm-identicon` to `dividat/elm-identicon`, this would actually be `1.0.0`.

2019-10-14 13:29 UTC, krksgbr commented on example/elm.json
> +    "elm-version": "0.19.0",
No reason, I'll relax it.

2019-10-14 13:38 UTC, krksgbr commented on elm.json
> +    "version": "4.0.0",
Hmm... Since this is a fork, we already have a `1.0.0` tag.

2019-10-15 08:33 UTC, knuton commented on elm.json
> +    "version": "4.0.0",
Ah, right, it will demand `1.0.0`. Since this is a fork and nothing points to the tags, we can delete them and start over.

2019-10-15 11:56 UTC, knuton approved these changes

2019-10-15 11:57 UTC, merged